### ISSUE TITLE
[Major Bug] Of one timestep all 3 photos are the same

### ISSUE THREAD

**Issue by Sodamin** [tum-autonomousdriving/autonomous-driving-simulator#1]
When running simulator_train/simulator.exe the 3 exported images in Data are the same for a single timestep.

![CapturedImage2](https://github.com/tum-autonomousdriving/autonomous-driving-simulator/assets/18659940/1d58e250-b344-4abb-bf6d-81f8e54f200a)
![CapturedImage3](https://github.com/tum-autonomousdriving/autonomous-driving-simulator/assets/18659940/ee1dfefa-2009-4001-9e98-fc101209261b)
![CapturedImage1](https://github.com/tum-autonomousdriving/autonomous-driving-simulator/assets/18659940/f854d425-0e5d-4df8-8271-b5274eca207c)

--------------------
System:
Win 11

**Comment by Einholz-Gao** [comment]
Oh， Thanks！In next Version I will fix it.

**Comment by Einholz-Gao** [comment]
![CapturedImage1](https://github.com/tum-autonomousdriving/autonomous-driving-simulator/assets/104414195/d11f72ee-aef7-4f9e-a59b-29f09df2430e)

To address the synchronization issue, I merged three images into one output, and the performance of the simulator has also improved. I have a question, though. It shouldn't be difficult for you to handle the data preprocessing, specifically splitting this combined image, right?

**Comment by Sodamin** [comment]
Nice one - super fast! Year splitting it should be fine :) 
Thanks!
