### ISSUE TITLE
[Suggestion] Put cameras higher

### ISSUE THREAD

**Issue by Sodamin** [tum-autonomousdriving/autonomous-driving-simulator#12]
Ferdinand and me would like to propose to put the cameras of the vehicle higher. When trying to identify traffic lights or anything other than the road, the location of the cameras is suboptimal (esp. if you drive behind e.g. a bus with this Ferrari)

![CapturedImage](https://github.com/tum-autonomousdriving/autonomous-driving-simulator/assets/18659940/6d9bbc42-2a7d-4ac6-abbb-156479f32cd5)

We would like to suggest to put the cameras similarly to Tesla and other companies on top of the windshield. This is mainly about the middle front facing camera, but probably all 3 can be moved. 

<img width="395" alt="image" src="https://github.com/tum-autonomousdriving/autonomous-driving-simulator/assets/18659940/654a5cd8-cea4-4fc6-83e5-5bf1588cad16">

We have not tested this location yet so cannnot be sure of up or downsides. We should probably position the cameras rather like where they would be if we have a normal, and not a race car.

**Comment by Einholz-Gao** [comment]
You are right. We can try to use a normal car rather than a race car later. We have some other Car Models in that Project. Just See here [here](https://www.youtube.com/watch?v=sJR9cDwmbGQ) and you can have a look how can we add a NWH physic engine onto a car model.

**Comment by Einholz-Gao** [comment]
after we can drive another normal car but not the default race car.

**Comment by pranav-ap** [comment]
Hey, Are the traffic lights in the sim images clear enough to reasonably try and predict the signal? This is the first time I am working on this topic, so I am curious.

![image](https://github.com/tum-autonomousdriving/autonomous-driving-simulator/assets/11399494/3b68feee-ff1c-49ae-bfca-05057f4ed161)

what has been your experience, @Sodamin ?
