### ISSUE TITLE
[Performance issue] Drive script lags behind of simulator

### ISSUE THREAD

**Issue by tarikisildar** [tum-autonomousdriving/autonomous-driving-simulator#14]
My drive.py script is receiving at most 17-18 images per second. Without even running the model, it lags behind the actual simulator as in the image I added.

![image](https://github.com/tum-autonomousdriving/autonomous-driving-simulator/assets/36731977/25c4017b-be88-4be2-b74c-93e9bde9cd7f)

I can't really make sure about the reason without checking out the code. Can we add the unity project under this repository so we can point out potential performance improvements or bug fixes more easily?

**Comment by pranav-ap** [comment]
Are you facing this in a windows OS?

**Comment by tarikisildar** [comment]
> Are you facing this in a windows OS?

Yes

**Comment by Einholz-Gao** [comment]
Hi. If you need, this is the Project. PLS try it on Unity 2021.3.21f1 / 2021.3.25f1
[Unity ](https://drive.google.com/drive/folders/12qE0ap-LlFvte5U0bopnc-77NfibJfUh?usp=sharing)

**Comment by tarikisildar** [comment]
I found the issue. On ServerInputProvider.cs
Start calls -> InvokeRepeating("CaptureAndSendImage", 0.0f, 0.05f)
which making computation and sends image unrelated from the current frame. 0.05 second makes 30 captures per second. And simulation runs around 15 fps, So in every frame, two images are sent. 

Removing that line and adding this

```c#
private void Update()
        {
            CaptureAndSendImage();
        }
``` 
solved it for me.

**Comment by Einholz-Gao** [comment]
This line is to limit the frequency of image transmission and prevent the emulator from freezing. In my opinion we should find the best balance

**Comment by tarikisildar** [comment]
Well, it's not a limiting factor in this context. I have a pretty high-end device and the simulator is still on 15-20 ish fps. This line is making it send an image
