### ISSUE TITLE
Windows Version Doubt

### ISSUE THREAD

**Issue by pranav-ap** [tum-autonomousdriving/autonomous-driving-simulator#15]
Hello, 
Do both these links have the same version of windows simulator? If not, which one are we supposed to use?

![image](https://github.com/tum-autonomousdriving/autonomous-driving-simulator/assets/11399494/a7802a74-70e4-48bb-8471-6b09ce99de46)

Thanks

**Comment by Sodamin** [comment]
@Einholz-Gao  that was me, which is the newest working one, should I change something?

**Comment by Sodamin** [comment]
(Pranav, for now, I am pretty sure you can use the experimental version if you wnat to work with it right away, it should be fine)

**Comment by Sodamin** [comment]
Checked with @Einholz-Gao they are now the same, will remove the link
