### ISSUE TITLE
Reversing Doubt

### ISSUE THREAD

**Issue by pranav-ap** [tum-autonomousdriving/autonomous-driving-simulator#16]
Hey,
Braking is working properly, but how can we reverse the car?  
Thanks

**Comment by Einholz-Gao** [comment]
Yeah. But you need to press "F" twice, and then press "S" (Hang up the reverse gear)
If you want to drive forward again, press "R" twice and drive with WASD key

**Comment by Einholz-Gao** [comment]
I will update it into the README, thanks!
