### ISSUE TITLE
Manual control during Test Mode

### ISSUE THREAD

**Issue by pranav-ap** [tum-autonomousdriving/autonomous-driving-simulator#17]
Is is possible to control the car manually during test mode? This can be handy while testing.
For example, if the car gets stuck somewhere, we can manually get it out, then let the model take over.

**Comment by Sodamin** [comment]
Hey Pranav, 
before implementing this in the simulator maybe something we did could be helpful: We have a text file next to the model and added the following in code:
- if it is empty, the model runs normally
- if there are values in, our controller takes the two values (first one being steering, second throttle)

We used this for general testing, but I think it could be that one cannot go backwards - did not test that.

Maybe that is rather the feature, going backwards?
