### ISSUE TITLE
Black Screen in 0.23v Windows

### ISSUE THREAD

**Issue by pranav-ap** [tum-autonomousdriving/autonomous-driving-simulator#18]
Hi,
I tried the latest version 0.23 on windows. I got a black screen, but the red text about speed was visible.
The saved images from the camera were all black too.

**Comment by Sodamin** [comment]
@Einholz-Gao seems like I will have to compile the new version for windows again, will try today

**Comment by Einholz-Gao** [comment]
It seems like, the built unity projects on my PC can not be opened successfully. We can wait the new built one from Michael.  Thanks Michael!

**Comment by Sodamin** [comment]
I added the new build here: https://drive.google.com/file/d/1gVAqzpiHZ_M5mUqed9nTLc_OsjXa0Hjv/view?usp=sharing and my tests worked out well

**Comment by pranav-ap** [comment]
Looks like the new version is working. Thank you
