### ISSUE TITLE
[Major Bug] Only 8 images get created per second

### ISSUE THREAD

**Issue by Sodamin** [tum-autonomousdriving/autonomous-driving-simulator#2]
I ran the simulator once for 30s and once for 60s it created just 8 Image sets per second. I think this is probably quite few compared to the Udacity simulator and might lead to bad control performane?

------------------
System
Win11
AMD Ryzen 7 7700X 8-Core at 4,5 GHz
RTX 3090

**Comment by Einholz-Gao** [comment]
Yea, it's true. I'm working on enhancing my performance. 
Btw, I'd like to know the appropriate image size for your training (for example: 640*480)

**Comment by Sodamin** [comment]
So the current ones from udacity are 320 × 160.
So fa the resolution was enough, but we might get problems with traffic lights.

Maybe we can for now keep the resolution and we should downsample all images if we need less. only if you need to go down because of the performance - and then I think it won't be a big issue

**Comment by Einholz-Gao** [comment]
I have already increased the sampling frequency, but unfortunately, I cannot go beyond 20 frames per second. This is because I need to strike a balance between the performance of the simulator and the sampling frequency.

**Comment by Sodamin** [comment]
Hmm I understand. Just a small one: I noticed motion blur, maybe removing that is just another small step to better performance?

Also: I am interested how others are doing with weaker hardware if someone can comment here

**Comment by Einholz-Gao** [comment]
Yeah now I close the Motion blur. Thanks for the suggestion!
And: I build this project with a small window size(640*480), and hope it can run smoother on weaker hardware. If it's too small for you, please write to me.
