### ISSUE TITLE
Traffic Lights Image Clarity

### ISSUE THREAD

**Issue by pranav-ap** [tum-autonomousdriving/autonomous-driving-simulator#21]
Hey,

I have not tried to perform traffic light classification yet. I just wanted to know other's experience.

The traffic lights from the dataset don't seem clear enough to make reliable predictions. The signal only seems to become clear once you get quite close to the signal. 

What do you think?

![image](https://github.com/tum-autonomousdriving/autonomous-driving-simulator/assets/11399494/df81d1e3-6484-427f-9380-065764e77df2)

Thanks

**Comment by MichaelSodamin** [comment]
It's right at the edge... we are able to just about early enough identify the light and stop before entering the cross section, but required some work. I was afraid the performance drops more if we render out larger images.

Cars like Teslas apparently use different focal lengths / zoom levels of their forward facing cameras, that would maybe also be a good addition. (but again hard on weaker hardware maybe)
<img width="1273" alt="image" src="https://github.com/tum-autonomousdriving/autonomous-driving-simulator/assets/48905580/62b77a25-6f09-47e6-b8bb-d484961df82c">

Do you want to give it a go with the current version, it is for sure possible. (and tbh it surprised me as well)

**Comment by pranav-ap** [comment]
Okay, I'll try it out!

**Comment by pranav-ap** [comment]
I have a general doubt. When we can see multiple traffic signals, how do can we train a model to choose the right one in order to make a decision?
