### ISSUE TITLE
Windows Build v0.24

### ISSUE THREAD

**Issue by pranav-ap** [tum-autonomousdriving/autonomous-driving-simulator#25]
Hey, 
When will the windows build for v0.24 be uploaded?
Thanks!

**Comment by Sodamin** [comment]
Maybe you can help us check out if this version works as expected on Windows: https://drive.google.com/file/d/1Y-rzQxAlZEkeNZB0RbqP9Jrt6lc2vMHJ/view?usp=drive_link

**Comment by pranav-ap** [comment]
I noticed the  following issues,

1. The menu are not aligned.
2. Once I go into train mode after pressing the train button, the car controls do not work

![image](https://github.com/tum-autonomousdriving/autonomous-driving-simulator/assets/11399494/ed604ad4-b1ce-4593-b502-bb7837426063)

**Comment by Sodamin** [comment]
Interesting that the window resized smaller. (can you resize it?)

**Comment by pranav-ap** [comment]
No, I cannot

**Comment by Sodamin** [comment]
Tried to fix it: https://drive.google.com/file/d/1XkrZCmOnyZno91qeEYNEEgKzhrm31vjz/view?usp=drive_link

- Weird that it did not drive for you... changed some stuff, worked for me. tested train and test again...
- Also resized the UI elements and you should now be able to resize it later (window starts way bigger for me)

**Comment by pranav-ap** [comment]
Yup, Now I'm able to control the vehicle and UI is also proper when I open.

**Comment by Sodamin** [comment]
Great!

Small update: (record icon initialized as active, but should have been off)
https://drive.google.com/file/d/1c8ZGFmXQltKOaCm14XrKahtA6FC9AgUZ/view?usp=drive_link (you don't need to test this one)
