### ISSUE TITLE
IP Doubt

### ISSUE THREAD

**Issue by pranav-ap** [tum-autonomousdriving/autonomous-driving-simulator#26]
Hey,

What is the below line supposed to be while using the v0.23 simulator in windows?

`eventlet.wsgi.server(eventlet.listen(("", 4567)), app) `

The IP text file says : 192.168.2.224

The car is not moving.

Thanks

**Comment by Sodamin** [comment]
The line in the code should be fine (we have the same)
the IP in the file should be changed to your IP

**Comment by Sodamin** [comment]
Actually you can just put in "localhost" (without " )

**Comment by pranav-ap** [comment]
I get the following line, and thats it. No change after that.

![image](https://github.com/tum-autonomousdriving/autonomous-driving-simulator/assets/11399494/c2bc31e3-2295-4afe-8502-a54ed3f0a2a4)

Kinda weird.

**Comment by Sodamin** [comment]
so far so good. I have the same, when I then start the simulator the python starts to receive images.

What might be a problem are your firewall / network settings. I am not sure what to do exactly but you must make sure the program is allowed to be reached... I think there were similar problems on the other simulator (from udacity) maybe you find material on that
