### ISSUE TITLE
Prediction

### ISSUE THREAD

**Issue by pranav-ap** [tum-autonomousdriving/autonomous-driving-simulator#27]
Small doubt. Where are we supposed to use our models to perform prediction and decide things?

```
@sio.on("vehicle_data")
def vehicle_command(sid, data):
```

or 
```

@sio.on("send_image")
def on_image(sid, data):
```

**Comment by Yuzou0317** [comment]
I think we should train the model using images with commands(steering, throttle, brake) labels, then import our trained neural network model into a Python file, with @sio.on("send_image")
def on_image(sid, data) we receive the pictures from unity and give these as input to our model and then predict the corresponding commands to send to the Unity client.
