### ISSUE TITLE
[Minor Bug] Vehicles sometimes disappear

### ISSUE THREAD

**Issue by Sodamin** [tum-autonomousdriving/autonomous-driving-simulator#3]
Single vehicels and sometimes all from the current view dissapear. Happens every about 15s.

------------
System
Win 11

**Comment by Einholz-Gao** [comment]
It's a bug of the traffic system. I have confidence in building a new model and resolving the issue at hand.

**Comment by Einholz-Gao** [comment]
That's because of the "Self Destroy in Distance". Now I think it is fixed. It will after a longer trip and then disappear... If it's still not enough, please tell me here and I will make it loooooooooger
