### ISSUE TITLE
[Minor Bug] Lag in the simulation every few seconds

### ISSUE THREAD

**Issue by Sodamin** [tum-autonomousdriving/autonomous-driving-simulator#4]
Every few seconds there is a lag / jitter in the simulation. I don't know yet if this might influence the recorded data. This can sometimes become very intense.
-------------------- 
**System**
Win11
AMD Ryzen 7 7700X 8-Core at 4,5 GHz
RTX 3090

**Comment by Einholz-Gao** [comment]
it could be a problem... During the driving and recording, saving the data, it happens. Later I will find a good way to make it smoother.

**Comment by Einholz-Gao** [comment]
Next version will be much better!
Storing the images was consuming a lot of system resources, but after I changed the strategy, the situation has improved significantly.

**Comment by Sodamin** [comment]
Nice!
