### ISSUE TITLE
[Question] How are the Releases planned?

### ISSUE THREAD

**Issue by Sodamin** [tum-autonomousdriving/autonomous-driving-simulator#6]
I wanted to ask how often you will release - and when you do how will we get informed to download the new version?

**Comment by Einholz-Gao** [comment]
maybe onece a week or 2 weeks. I'm glad to hear about your user experience and error reports. Thank you for sharing your feedback!

**Comment by Einholz-Gao** [comment]
Maybe once a week or 2 weeks. If it's updated, I will publish it in Wechat. Don't worry about that.
 I'm glad to hear about your user experience and error reports. Thank you for sharing your feedback!
It's also a nice experience for my development...
