### ISSUE TITLE
[Minor Bug] Last training image not saved but logged

### ISSUE THREAD

**Issue by Sodamin** [tum-autonomousdriving/autonomous-driving-simulator#7]
Hey, 

I can happen that when closing the simulator to stop the simulation, the last image gets registered in the VehicleData.txt but is not saved by the simulator (the sub folder does not even exist).

This creates issues when digesting the data.

Thanks!

**Comment by Einholz-Gao** [comment]
Thanks! I will check the workflow of saving images and the VehicleData.

**Comment by Einholz-Gao** [comment]
This issue is solved. Later a new version will be uploaded.
