### ISSUE TITLE
Windows Simulator Doesn't Load - Black Screen

### ISSUE THREAD

**Issue by BaranEkin** [tum-autonomousdriving/autonomous-driving-simulator#8]
On Windows 11 system, when Simulator.exe is clicked, small window appears with "made with unity" intro and then it shows just a black window and nothing happens. I used simulator v0.2

**Comment by Sodamin** [comment]
+1 
Same for me, just having this greyish background after logo.

**Comment by pranav-ap** [comment]
+1 
This problem still persists in my Windows system with the latest sim version.

**Comment by Einholz-Gao** [comment]
Thanks for reply, I will try to fix it again. V0.1 can be opened.

**Comment by Sodamin** [comment]
correct, some more debugging help: the recording starts but even the recorded pictures are black. i can also share my screen with you if you want

**Comment by Einholz-Gao** [comment]
Now it works well, right?

**Comment by ge49nuk** [comment]
For me it works now!

**Comment by pranav-ap** [comment]
Thanks for the fix

**Comment by BaranEkin** [comment]
Yes, it works, thanks!
