### ISSUE TITLE
Mac Simulator_train/test can't be opened

### ISSUE THREAD

**Issue by csahincs** [tum-autonomousdriving/autonomous-driving-simulator#9]
I have downloaded the Simulator test and train builds for Mac, but both cannot be opened on Mac.

**Comment by Einholz-Gao** [comment]
can v0.1 be opened, right? I will check it. Thanks!

**Comment by Sodamin** [comment]
correct, some more debugging help: the recording starts but even the recorded pictures are black. i can also share my screen with you if you want

**Comment by csahincs** [comment]
v0.21 is working, thanks for the fast resolve. Can you enable window resizing for builds?

**Comment by Einholz-Gao** [comment]
next version I will try. Because before this may be the cause of the black screen, so I cancel it
